version: "3.8"
services:
  terraform:
    image: hashicorp/terraform:1.3.1
    container_name: my-aws-terraform
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - ./src:/opt/
    working_dir: /opt/
