version: 2.1

orbs:
  terraform: circleci/terraform@3.2.0

jobs:
  fmt:
    executor:
      name: terraform/default
      tag: 1.0.5
    steps:
      - checkout
      - terraform/fmt:
          path: src/
          recursive: true
  validate:
    executor:
      name: terraform/default
      tag: 1.0.5
    steps:
      - checkout
      - terraform/init:
          path: src/
          backend: false
      - terraform/validate:
          path: src/

workflows:
  version: 2
  code_check:
    jobs:
      - fmt
      - validate
